@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.zerognetwork.enhancedchattags;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;