modLoader="javafml"
loaderVersion="[46,)"

license="All Rights Reserved"
issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"
showAsResourcePack=false

[[mods]]
  modId="enhancedchattags"
  version="1.0.1"
  displayName="Enhanced Chat Tags"
  updateJSONURL="https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json"
  displayURL="https://minecraftforge.net"
  logoFile="logo.png"
  credits="I'd like to thank my mother and father."
  authors="MrWhiteFlamesYT"
  description='''
  EnhancedChatTags is a server-side Minecraft mod that revolutionizes in-game communication. It offers advanced chat formatting and dynamic player tag management, seamlessly integrating with LuckPerms and MC2Discord. Customize your server's chat appearance and player displays with ease, enhancing the overall multiplayer experience. Features include custom chat formatting with support for color codes and gradients, player tags above or below names, LuckPerms integration for prefix and suffix support, MC2Discord compatibility for seamless Discord integration, and configurable chat and tag formats via TOML configuration file.
  '''
  displayTest="MATCH_VERSION"

[[dependencies.enhancedchattags]]
  modId="forge"
  mandatory=true
  versionRange="[46,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.enhancedchattags]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20,)"
  ordering="NONE"
  side="BOTH"
