modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="enhancedchattags"
version="1.0.0"
displayName="Enhanced Chat Tags"
authors="ZeroG Network"
description='''
EnhancedChatTags is a server-side Minecraft mod that revolutionizes in-game communication. It offers advanced chat formatting and dynamic player tag management, seamlessly integrating with LuckPerms. Customize your server's chat appearance and player displays with ease, enhancing the overall multiplayer experience.
'''

[[dependencies.enhancedchattags]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.enhancedchattags]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="SERVER"

[[dependencies.enhancedchattags]]
    modId="luckperms"
    mandatory=true
    versionRange="[5.4,)"
    ordering="NONE"
    side="SERVER"